[package]
name = "casper-name-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { workspace = true }
odra-casper-livenet-env = { workspace = true }
odra-cli = { workspace = true }
odra-modules = { workspace = true }
casper-name-contracts = { path = "../casper-name-contracts" }
clap = { version = "4.5.4", features = ["derive"] }
prettycli = "0.1.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = { version = "1.0", features = ["default"] }
serde_json = "1.0"
toml = "0.8.13"
blake2 = "0.10.6"
hex = "0.4.3"

[[bin]]
name = "casper-name-cli"
path = "bin/main.rs"
