[workspace]
members = [
    "casper-name-cli",
    "casper-name-contracts",
]

resolver = "2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
strip = true

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
casper-types = { version = "5.0.0", git = "https://github.com/casper-network/casper-node", branch = "rustSDK-feat-2.0" }
