[package]
name = "casper-name"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { path = "../odra2/odra", features = [], default-features = false }
odra-modules = { path = "../odra2/modules", features = [], default-features = false }
hex = { version = "0.4.3", default-features = false }
odra-casper-livenet-env = { path = "../odra2/odra-casper/livenet-env", optional = true }

[dev-dependencies]
odra-test = { path = "../odra2/odra-test", features = [], default-features = false }

[build-dependencies]
odra-build = { path = "../odra2/odra-build", features = [], default-features = false }

[features]
default = []
livenet = ["odra-casper-livenet-env"]

[[bin]]
name = "casper_name_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "casper_name_build_schema"
path = "bin/build_schema.rs"
test = false

[[bin]]
name = "deploy-example"
path = "bin/deploy_example.rs"
required-features = ["livenet"]
test = false

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
