[[contracts]]
fqn = "casper_name::contracts::registrar::Registrar"

[[contracts]]
fqn = "casper_name::contracts::name_token::NameToken"

[[contracts]]
fqn = "casper_name::contracts::controller::Controller"
