[package]
name = "casper-name-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { git = "https://github.com/odradev/odra", branch = "release/1.3.0",  features = [], default-features = false }
odra-modules = { git = "https://github.com/odradev/odra", branch = "release/1.3.0", features = [], default-features = false }
hex = { version = "0.4.3", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
serde-json-wasm = { version = "1", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-build = { git = "https://github.com/odradev/odra", branch = "release/1.3.0" }

[dev-dependencies]
odra-test = { git = "https://github.com/odradev/odra", branch = "release/1.3.0", features = [], default-features = false }
blake2 = "0.10.6"
hex = "0.4.3"

[build-dependencies]
odra-build = { git = "https://github.com/odradev/odra", branch = "release/1.3.0", features = [], default-features = false }

[[bin]]
name = "casper_name_contracts_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "casper-name-contracts_build_schema"
path = "bin/build_schema.rs"
test = false

[[bin]]
name = "structs-as-bytes"
path = "bin/structs_as_bytes.rs"
test = false

# [[bin]]
# name = "test-schema"
# path = "bin/test_schema.rs"
# test = false

# [[test]]
# name = "test_register"
# path = "tests/test_register.rs"

