@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "D3 admin"
participant "Registrar"
participant "NameToken"
boundary "Events"

== [Admin] Transfer a domain ==

"D3 admin" -> "Registrar": admin_transfer(new_owner, cspr_names[])
activate Registrar
loop N times
    Registrar -> NameToken: transfer(new_oner, name_hash)
    activate NameToken
NameToken -> NameToken: check expiration date
alt expiration < blocktime
    NameToken ->X "D3 admin": Revert with cannot_transfer error
end
    NameToken -> NameToken: clear resolver
    NameToken -> "Events": MetadataUpdated event
    NameToken -> NameToken: clear operator
    NameToken -> NameToken : set new owner
    NameToken -> "Events": Transfer event
    NameToken -> Registrar
    deactivate NameToken
end
Registrar -> "D3 admin"
deactivate Registrar

@enduml
