@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "D3 admin"
participant "Registrar"
participant "Registry"
boundary "Events"

== [Admin] Transfer a domain ==

"D3 admin" -> "Registrar": admin_transfer(new_owner, cspr_names[])
activate Registrar
loop N times
    Registrar -> Registry: transfer(new_oner, cspr_name_token_id)
    activate Registry
    Registry -> Registry: clear resolver
    Registry -> "Events": MetadataUpdated event
    Registry -> Registry: clear operator
    Registry -> Registry : set new owner
    Registry -> "Events": Transfer event
    Registry -> Registrar
    deactivate Registry
end
Registrar -> "D3 admin"
deactivate Registrar

@enduml
