@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "D3 admin"
participant "Registrar"
participant "NameToken"
boundary "Events"

== [Admin] Burn a domain ==

"D3 admin" -> "Registrar": admin_burn(name_hashes[])
activate Registrar
loop N times
    Registrar -> NameToken: burn(name_hash)
    activate NameToken
    NameToken -> NameToken: clear resolver
    NameToken -> "Events": MetadataUpdated event
    NameToken -> NameToken: burn token
    NameToken -> "Events": Burn event
    NameToken -> Registrar
    deactivate NameToken
end
Registrar -> "D3 admin"
deactivate Registrar

@enduml
