@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "Registrar"
participant "NameToken"
participant "Resolver"
boundary "Events"

== Buy a *cspr name from D3 Marketplace with fiat payment ==

User -> d3: Buy *cspr name
activate d3
d3 -> d3: process fiat payment
d3 -> User
deactivate d3

d3 -> Registrar: secondarySale(SecondarySaleVoucher, sig)
activate Registrar
Registrar -> Registrar: verify voucher
Registrar -> NameToken: transfer(seller, buyer, name_hash)
activate NameToken
NameToken -> NameToken: clear Resolver
NameToken -> "Events": MetadataUpdated event
NameToken -> NameToken: transfer token
NameToken -> "Events": Transfer event
NameToken -> Registrar
deactivate NameToken
Registrar -> d3
deactivate Registrar
deactivate d3

== ==
@enduml
