@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "D3 Operator" as d3Op
participant "NameToken"
participant "Registrar"
boundary "Events"

== Buy *cspr names from D3 Marketplace with CSPR payment ==

User -> d3: Buy *cspr name
activate d3
d3 -> User: signed SecondarySaleVoucher
deactivate d3

User -> d3Op: secondarySale(SecondarySaleVoucher, sig)
activate d3Op
d3Op -> d3Op: verify voucher expiration
d3Op -> d3Op: verify voucher signature
d3Op -> d3Op: process CSPR payment
d3Op -> "Events": Payment event
loop N times
    d3Op -> NameToken: transfer(seller, buyer, name_hash)
    activate NameToken
    NameToken -> NameToken: check expiration date
    alt expiration < blocktime
        NameToken ->X d3Op: Revert with cannot_transfer error
    end
    NameToken -> NameToken: clear Resolver
    NameToken -> "Events": MetadataUpdated event
    NameToken -> NameToken: clear operator
    NameToken -> NameToken : set new owner
    NameToken -> "Events": Transfer event
    NameToken -> d3Op
    deactivate NameToken
end
d3Op -> User
deactivate d3

== ==

@enduml
