@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Contract owner"
participant "D3 operator" as d3op

== Set treasury account ==

"Contract owner" -> d3op: set_treasury(account_hash)
activate d3op
d3op -> d3op: set treasury account
"d3op" -> "Contract owner"
deactivate d3op

== ==

@enduml
