@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Contract owner"
participant "D3 operator" as d3op

== Set voucher signer ==

"Contract owner" -> d3op: set_signer(public_key)
activate d3op
d3op -> d3op: set signer key
"d3op" -> "Contract owner"
deactivate d3op

== ==

@enduml
