@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Anyone"
participant "Registrar"
participant "Registry"
boundary "Events"

== Expire a domain ==

"Anyone" -> "Registrar": expire(cspr_name)
activate Registrar
Registrar -> Registry: metadata(cspr_name_token_id)
Registry -> Registrar
Registrar -> Registrar: Check expiry date
group expiry date > blocktime
    Registrar -> Registry: burn(cspr_name_token_id)
    activate Registry
    Registry -> Registry: Clear resolver
    Registry -> "Events": MetadataUpdated event
    Registry -> Registry: burn token
    Registry -> "Events": Burn event
    Registry -> Registrar
    deactivate Registry
end
Registrar -> "Anyone"

@enduml
