@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Anyone
participant "Reverse Resolver"

== Lookup account name ==

Anyone -> "Reverse Resolver": name()
activate "Reverse Resolver"
"Reverse Resolver" -> Anyone
deactivate "Reverse Resolver"

@enduml
