@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "Registrar"
participant "NameToken"
boundary "Events"

== Buy multiple (N) *cspr names with fiat currency ==

User -> d3: Buy N *cspr names
activate d3
d3 -> d3: process fiat payment
d3 -> User
deactivate d3

d3 -> Registrar: register(TokenizationVoucher)
activate Registrar
Registrar -> Registrar: verify voucher\nexpiration
    loop N times
    Registrar -> NameToken: metadata(name_hash)
    NameToken -> Registrar
        alt Token exists
            Registrar -> Registrar: check expiration date
            alt expiration+grace_period+pending_delete_period < blocktime
                Registrar -> NameToken: burn(name_hash)
                NameToken -> NameToken: clear resolver
                NameToken -> "Events": MetadataUpdated event
                NameToken -> NameToken: burn token
                NameToken -> "Events": Burn event
            else expiration+grace_period+pending_delete_period > blocktime
                Registrar ->x d3: Revert with\nnot expired token error
            end
        end
        Registrar -> NameToken: mint(buyer, metadata)
        activate NameToken
        NameToken -> NameToken: mint token
        NameToken -> "Events": Mint event
        NameToken -> Registrar
        deactivate NameToken
    end loop
Registrar -> d3
deactivate Registrar
deactivate d3

@enduml
