@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Owner
participant "d3.app" as d3 #lightblue
participant "Registrar"
participant "Registry"
boundary "Events"

== Renew a *cspr name with fiat currency ==

Owner -> d3: Renew *cspr name
activate d3
d3 -> d3: Process fiat payment
d3 -> Owner
deactivate d3

d3 -> Registrar: renew(RenewalVoucher, sig)
activate Registrar
Registrar -> Registrar: verify voucher
Registrar -> Registry: set_token_metadata(new_metadata)
activate Registry
Registry -> Registry: update metadata
Registry -> "Events": MetadataUpdated event
Registry -> Registrar
deactivate Registry
Registrar -> d3
deactivate Registrar
deactivate d3

@enduml
