@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "Registrar"
participant "NameToken"
boundary "Events"

== Buy and renew multiple *cspr names with fiat currency ==

User -> d3: Renew N *cspr names\nand buy M *cspr names
activate d3
d3 -> d3: process fiat payment
d3 -> User
deactivate d3

d3 -> Registrar: admin_prolong_and_register(Vec<TokenRenewalInfo>, Vec<NameMintInfo>)
activate Registrar
    loop N times
        note over Registrar: Same flow as for admin_prolong().
    end loop
    loop M times
        note over Registrar: Same flow as for admin_register().
    end loop
Registrar -> d3

deactivate Registrar
deactivate d3

@enduml
