@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Owner
participant "d3.app" as d3 #lightblue
participant "Registrar"
participant "Registry"
boundary "Events"

== Renew a *cspr name with fiat currency ==

Owner -> d3: Renew *cspr name
activate d3
d3 -> d3: process fiat payment
d3 -> Owner
deactivate d3

d3 -> Registrar: renew(RenewalVoucher)
activate Registrar
Registrar -> Registrar: verify voucher\nexpiration
Registrar -> Registry: get_token_metadata(name_hash)
Registry -> Registrar
Registrar -> Registrar: check expiration date
alt expiration+grace_period < blocktime
    Registrar -> Registry: burn(name_hash)
    Registry -> Registry: Clear resolver
    Registry -> "Events": MetadataUpdated event
    Registry -> Registry: burn token
    Registry -> "Events": Burn event
    Registrar ->x d3: Revert with\ngrace_period_expired\nerror
end
Registrar -> Registry: set_token_metadata(new_metadata)
activate Registry
Registry -> Registry: update metadata
Registry -> "Events": MetadataUpdated event
Registry -> Registrar
deactivate Registry
Registrar -> d3
deactivate Registrar
deactivate d3

@enduml
