@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "Controller"
participant "Registrar"
participant "Registry"
participant "Resolver"
boundary "Events"

== Onchain purchase ==

User -> d3: Buy *cspr name with CSPR
d3 -> User: signed PaymentVoucher
User -> Controller: buy(PaymentVoucher)
activate Controller
Controller -> Controller: verify voucher
Controller -> Controller: Process CSPR payment
Controller -> "Events": Payment event
Controller -> Registrar: register(PaymentVoucher)
activate Registrar
Registrar -> Registrar: verify voucher
Registrar -> Registry: mint(to, metadata)
activate Registry
Registry -> Registry: mint token
Registry -> "Events": Mint event
Registry -> Registrar
deactivate Registry
Registrar -> Controller
deactivate Registrar
Controller -> User
deactivate Controller

@enduml
