@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "d3.app" as d3 #lightblue
participant "Controller"
participant "Registrar"
participant "NameToken"
boundary "Events"

== Buy multiple *cspr names with CSPR token ==

User -> d3: Buy N *cspr names with CSPR
activate d3
d3 -> User: signed PaymentVoucher
deactivate d3

User -> Controller: buy(PaymentVoucher, sig)
activate Controller
Controller -> Controller: verify voucher\nexpiration
Controller -> Controller: verify voucher\nsignature
Controller -> Controller: process CSPR payment
Controller -> "Events": PaymentFulfilled event
Controller -> Registrar: register(TokenizationVoucher)
activate Registrar
Registrar -> Registrar: verify voucher\nexpiration
    loop N times
        Registrar -> NameToken: metadata(name_hash)
        NameToken -> Registrar
        alt Token exists
            Registrar -> Registrar: check expiration date
            alt expiration+grace_period+pending_delete_period < blocktime
                Registrar -> NameToken: burn(name_hash)
                NameToken -> NameToken: clear resolver address
                NameToken -> "Events": MetadataUpdated event
                NameToken -> NameToken: burn token
                NameToken -> "Events": Burn event
            else expiration+grace_period+pending_delete_period > blocktime
                Registrar ->x d3: Revert with\nnot expired token error
            end
        end
        Registrar -> NameToken: mint(buyer, metadata)
        activate NameToken
        NameToken -> NameToken: mint token
        NameToken -> "Events": Mint event
        NameToken -> Registrar
        deactivate NameToken
    end loop
Registrar -> Controller
deactivate Registrar
Controller -> User
deactivate Controller

@enduml
