@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Owner
participant "d3.app" as d3 #lightblue
participant "Controller"
participant "Registrar"
participant "Registry"
boundary "Events"

== Renew a *cspr name with CSPR token payment ==

Owner -> d3: Buy *cspr name with CSPR
activate d3
d3 -> Owner: signed RenewalVoucher
deactivate d3

Owner -> Controller: renew(RenewalVoucher, sig)
activate Controller
Controller -> Controller: Process CSPR payment
Controller -> "Events": Payment event
Controller -> Registrar: renew(RenewalVoucher, sig)
activate Registrar
Registrar -> Registry: set_token_metadata(new_metadata)
activate Registry
Registry -> Registry: update metadata
Registry -> "Events": MetadataUpdated event
Registry -> Registrar
deactivate Registry
Registrar -> Controller
deactivate Registrar
Controller -> Owner
deactivate Controller

@enduml
