@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "Controller"
participant "Registrar"
participant "Registry"
participant "Resolver"

== Onchain purchase ==

User -> Controller: Buy
activate Controller
Controller -> Controller: Process CSPR payment
Controller -> Registrar: Register
activate Registrar
Registrar -> Registry: mint()
activate Registry
Registry -> Registry: mint token
Registry -> Registrar
deactivate Registry
Registrar -> Controller
deactivate Registrar
Controller -> User
deactivate Controller

@enduml
