@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Owner
participant "d3.app" as d3 #lightblue
participant "Controller"
participant "Registrar"
participant "NameToken"
boundary "Events"

== Renew a *cspr name with CSPR token payment ==

Owner -> d3: Buy *cspr name with CSPR
activate d3
d3 -> Owner: signed RenewalVoucher
deactivate d3

Owner -> Controller: renew(RenewalVoucher, sig)
activate Controller
Controller -> Controller: verify voucher\nexpiration
Controller -> Controller: verify voucher\nsignature
Controller -> Controller: process CSPR payment
Controller -> "Events": Payment event
Controller -> Registrar: renew(RenewalVoucher, sig)
activate Registrar
Registrar -> Registrar: verify voucher\nexpiration
Registrar -> NameToken: metadata(name_hash)
NameToken -> Registrar
Registrar -> Registrar: check expiration date
alt expiration+grace_period < blocktime
    Registrar -> NameToken: burn(name_hash)
    NameToken -> NameToken: clear resolver
    NameToken -> "Events": MetadataUpdated event
    NameToken -> NameToken: burn token
    NameToken -> "Events": Burn event
    Registrar ->x d3: Revert with\ngrace_period_expired\nerror
end
Registrar -> NameToken: set_token_metadata(name_hash, new_metadata)
activate NameToken
NameToken -> Registry: update metadata
Registry -> "Events": MetadataUpdated event
Registry -> Registrar
deactivate Registry
Registrar -> Controller
deactivate Registrar
Controller -> Owner
deactivate Controller

@enduml
