@startuml
'https://plantuml.com/sequence-diagram

'autonumber
participant "Contract" #lightblue
participant "NameToken"
participant "Resolver"

== On-chain name resolution ==

activate "Contract"
"Contract" -> "NameToken": metadata(name_hash)
"NameToken" -> "Contract"
Contract -> Contract: check expiry date
Contract -> Contract: extract resolver address

group blocktime < expiry date
"Contract" -> Resolver: resolve(full_domain)
alt no resolution found
    Resolver -> Contract: None
end
Resolver -> Contract: Some(address)
end
== ==

deactivate Contract

@enduml
