@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Contract owner"
participant "Controller"

== Set treasury account ==

"Contract owner" -> Controller: set_treasury(account_hash)
activate Controller
Controller -> Controller: set treasury account
"Controller" -> "Contract owner"
deactivate Controller

== ==

@enduml
