@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "NameToken Admin"
participant "NameToken"
boundary "Events"

== Set transfer filter contract ==

"NameToken Admin" -> "Registry": set_transfer_filter(contract_package_hash)
activate "Registry"
Registry -> Registry: set filter contract
Registry -> "Events": VariablesSet event
"Registry" -> "Registry Admin"
deactivate "Registry"

@enduml
