@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Registrar admin"
participant "Registrar"

== Set grace period time span ==

"Registrar admin" -> "Registrar": set_grace_period(timespan)
activate "Registrar"
"Registrar" -> "Registrar": Update grace_period
"Registrar" -> "Registrar admin"
deactivate "Registrar"

@enduml
