@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor User
participant "Controller"
participant "Registrar"
participant "Registry"
boundary "Events"

== Set resolver ==

User -> Controller: Set resolver
activate Controller

Controller -> Registry: set_token_metadata()
activate Registry
Registry -> "Events": MetadataUpdated event
Registry -> Controller
deactivate Registry
Controller -> User
deactivate Controller
@enduml
