@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Domain owner"
participant "Controller"
participant "Registrar"
participant "Registry"
boundary "Events"

== Set resolver ==

"Domain owner" -> Controller: Set resolver
activate Controller

Controller -> Registry: set_token_metadata()
activate Registry
Registry -> "Events": MetadataUpdated event
Registry -> Controller
deactivate Registry
Controller -> "Domain owner"
deactivate Controller
@enduml
