@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Admin"
participant "NameToken"
boundary "Events"

== Set default resolver ==

"Admin" -> NameToken: set_default_resolver(resolver_address)
activate NameToken
NameToken -> NameToken: set default resolver
NameToken -> "Admin"
deactivate NameToken

== ==

@enduml
