@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Registry Admin"
participant "Registry"
boundary "Events"

== Set transfer filter contract ==

"Registry Admin" -> "Registry": set_transfer_filter(contract_package_hash)
activate "Registry"
Registry -> Registry: set filter contract
Registry -> "Events": VariablesSet event
"Registry" -> "Registry Admin"
deactivate "Registry"

@enduml
