@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Operator
participant "Registry"
boundary "Events"

== Transfer token by operator ==

Operator -> Registry: transfer(old_owner, new_owner, cspr_name_token_id)
activate Registry
Registry -> Registry: Clear resolver
Registry -> "Events": MetadataUpdated event
Registry -> Registry: Clear operator
Registry -> Registry : Set new owner
Registry -> "Events": Transfer event
Registry -> Operator
deactivate Registry

== ==

@enduml
