@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Operator
participant "NameToken"
boundary "Events"

== Transfer token by operator ==

Operator -> NameToken: transfer(old_owner, new_owner, name_hash)
activate NameToken
NameToken -> Registrar: can_transfer(name_hash)
Registrar -> NameToken
alt Cannot transfer
    NameToken ->X Operator: Revert with cannot_transfer error
end
NameToken -> NameToken: clear resolver
NameToken -> "Events": MetadataUpdated event
NameToken -> NameToken: clear operator
NameToken -> NameToken : set new owner
NameToken -> "Events": Transfer event
NameToken -> Operator
deactivate NameToken

== ==

@enduml
