@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Operator
participant "NameToken"
participant "Resolver"
boundary "Events"

== Transfer token by operator ==

Operator -> NameToken: transfer(old_owner, new_owner, name_hash)
activate NameToken
NameToken -> NameToken: check expiration date
alt expiration < blocktime
    NameToken ->X Operator: Revert with cannot_transfer error
end
alt Resolver is default resolver
    NameToken -> Resolver: cleanup(name_hash)
    Resolver -> NameToken:
else
    NameToken -> NameToken : set default resolver
    NameToken -> "Events": MetadataUpdated event
end
NameToken -> NameToken: clear operator
NameToken -> NameToken : set new owner
NameToken -> Resolver: cleanup(name_hash)
Resolver -> NameToken:
NameToken -> "Events": Transfer event
NameToken -> Operator
deactivate NameToken

== ==

@enduml
