@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Owner
participant "Registry"
boundary "Events"

== Transfer token ==

Owner -> Registry: transfer(new_owner, name_hash)
activate Registry
Registry -> Registrar: can_transfer(name_hash)
Registrar -> Registry
alt Cannot transfer
    Registry ->X Owner: Revert with cannot_transfer error
end
Registry -> Registry: clear resolver
Registry -> "Events": MetadataUpdated event
Registry -> Registry: clear operator
Registry -> Registry : set new owner
Registry -> "Events": Transfer event
Registry -> Owner
deactivate Registry

== ==

@enduml
