@startuml
'https://plantuml.com/sequence-diagram

'autonumber
participant "NameToken"
participant "Registrar"

== Transfer filter contract ==

NameToken -> Registrar: can_transfer(name_hash, old_owner, new_owner)
activate Registrar
Registrar -> NameToken: metadata(name_hash)
NameToken -> Registrar: token metadata
Registrar -> Registrar: check expiration date
alt expiration > blocktime
 Registrar -> NameToken: transfer allowed
else
 Registrar -> NameToken: cannot transfer
end
deactivate Registrar

== ==

@enduml
