@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor "Registrar admin"
participant "Registrar"

== Whitelist controller contract / admin address ==

"Registrar admin" -> "Registrar": whitelist_controller(hash_key[])
activate "Registrar"
"Registrar" -> "Registrar": Update ACL
"Registrar" -> "Registrar admin"
deactivate "Registrar"

@enduml
