@startuml
'https://plantuml.com/sequence-diagram

'autonumber
actor Admin
participant "Registry"
boundary "Events"

== Whitelist registrar contract ==

Admin -> "Registry": set_variables()
activate "Registry"
Registry -> "Events": VariablesSet event
"Registry" -> Admin
deactivate "Registry"

@enduml
